name: monappcompteur
description: Application de gestion locative
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  
  # Pour les PDF
  pdf: ^3.10.7
  path_provider: ^2.1.1
  
  # Pour le partage
  share_plus: ^7.2.2
  url_launcher: ^6.2.2

  # ... autres dépendances
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true